USE ROLE HOL2;
USE WAREHOUSE HOL2_WH;
USE SCHEMA HOL2_DB.HOL2_SCHEMA;

-- table creation
CREATE OR REPLACE TABLE HOL2_DB.HOL2_SCHEMA.DAILY_REVENUE (
	DATE DATE,
	REVENUE FLOAT,
	COGS FLOAT,
	FORECASTED_REVENUE FLOAT
);
CREATE OR REPLACE TABLE HOL2_DB.HOL2_SCHEMA.DAILY_REVENUE_BY_PRODUCT (
	DATE DATE,
	PRODUCT_LINE VARCHAR(16777216),
	REVENUE FLOAT,
	COGS FLOAT,
	FORECASTED_REVENUE FLOAT
);
CREATE OR REPLACE TABLE HOL2_DB.HOL2_SCHEMA.DAILY_REVENUE_BY_REGION (
	DATE DATE,
	SALES_REGION VARCHAR(16777216),
	REVENUE FLOAT,
	COGS FLOAT,
	FORECASTED_REVENUE FLOAT
);

-- load data into tables
PUT file://data/daily_revenue_combined.csv @RAW_DATA;
PUT file://data/daily_revenue_by_product_combined.csv @RAW_DATA;
PUT file://data/daily_revenue_by_region_combined.csv @RAW_DATA;

COPY INTO HOL2_DB.HOL2_SCHEMA.DAILY_REVENUE
FROM @RAW_DATA
FILES = ('daily_revenue_combined.csv.gz')
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
    EMPTY_FIELD_AS_NULL = FALSE
    error_on_column_count_mismatch=false
)

ON_ERROR=CONTINUE
FORCE = TRUE ;

COPY INTO HOL2_DB.HOL2_SCHEMA.DAILY_REVENUE_BY_PRODUCT
FROM @raw_data
FILES = ('daily_revenue_by_product_combined.csv.gz')
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
    EMPTY_FIELD_AS_NULL = FALSE
    error_on_column_count_mismatch=false
)

ON_ERROR=CONTINUE
FORCE = TRUE ;



COPY INTO HOL2_DB.HOL2_SCHEMA.DAILY_REVENUE_BY_REGION
FROM @raw_data
FILES = ('daily_revenue_by_region_combined.csv.gz')
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
    EMPTY_FIELD_AS_NULL = FALSE
    error_on_column_count_mismatch=false
)

ON_ERROR=CONTINUE
FORCE = TRUE ;

-- run this after creating skeleton semantic model through semantic-model-generator
PUT file://hol2_semantic_model_v1.yaml @SEMANTIC_MODEL AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://revenue_timeseries.yaml @SEMANTIC_MODEL AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
ls @SEMANTIC_MODEL; 